import { v1 } from 'uuid';
import { AccountType } from '../ui/Account';

export const accounts: AccountType[] = [
  {
    id: v1(),
    name: 'Буба',
    lastName: 'Бубенцов',
    photo: '1',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Илья',
    lastName: 'Анташкевич',
    photo: '2',
    info: 'Художник и иллюстратор. Рисую обаятельные и точные портреты из окружающей жизни.',
    status: 'Отчислен',
  },
  {
    id: v1(),
    name: 'Леброн',
    lastName: 'Джеймс',
    photo: '3',
    info: 'Звуковой художник, куратор и музыкальный продюсер. Работал как аранжировщик и композитор с популярными исполнителями.',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Натали',
    lastName: 'Трамп',
    photo: '4',
    info: 'Изучаю цифровой дизайн, программирование и управление проектами.',
    status: 'Обучается',
  },
  {
    id: v1(),
    name: 'Валентина',
    lastName: 'Матанина',
    photo: '5',
    info: 'Звуковой художник, куратор и музыкальный продюсер. Работал как аранжировщик и композитор с популярными исполнителями.',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Лев',
    lastName: 'Кошкин',
    photo: '6',
    info: 'Изучаю цифровой дизайн, программирование и управление проектами.',
    status: 'Отчислен',
  },
  {
    id: v1(),
    name: 'Антоха',
    lastName: 'Антонов',
    photo: '7',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Обучается',
  },
  {
    id: v1(),
    name: 'Александр',
    lastName: 'Александров',
    photo: '8',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis totam id dolorem reprehenderit perferendis, nostrum sequi quod consequatur veritatis? Numquam asperiores, aliquid sit natus quod dolorem autem. Eius, iste eveniet.',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Дим',
    lastName: 'Димыч',
    photo: '9',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Отчислен',
  },
  {
    id: v1(),
    name: 'Дядя',
    lastName: 'Фёдор',
    photo: '10',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Обучается',
  },
  {
    id: v1(),
    name: 'Буба',
    lastName: 'Бубенцов',
    photo: '11',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Илья',
    lastName: 'Анташкевич',
    photo: '12',
    info: 'Художник и иллюстратор. Рисую обаятельные и точные портреты из окружающей жизни.',
    status: 'Отчислен',
  },
  {
    id: v1(),
    name: 'Леброн',
    lastName: 'Джеймс',
    photo: '13',
    info: 'Звуковой художник, куратор и музыкальный продюсер. Работал как аранжировщик и композитор с популярными исполнителями.',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Натали',
    lastName: 'Трамп',
    photo: '14',
    info: 'Изучаю цифровой дизайн, программирование и управление проектами.',
    status: 'Обучается',
  },
  {
    id: v1(),
    name: 'Валентина',
    lastName: 'Матанина',
    photo: '15',
    info: 'Звуковой художник, куратор и музыкальный продюсер. Работал как аранжировщик и композитор с популярными исполнителями.',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Лев',
    lastName: 'Кошкин',
    photo: '16',
    info: 'Изучаю цифровой дизайн, программирование и управление проектами.',
    status: 'Отчислен',
  },
  {
    id: v1(),
    name: 'Антоха',
    lastName: 'Антонов',
    photo: '17',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Обучается',
  },
  {
    id: v1(),
    name: 'Александр',
    lastName: 'Александров',
    photo: '18',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis totam id dolorem reprehenderit perferendis, nostrum sequi quod consequatur veritatis? Numquam asperiores, aliquid sit natus quod dolorem autem. Eius, iste eveniet.',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Дим',
    lastName: 'Димыч',
    photo: '19',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Отчислен',
  },
  {
    id: v1(),
    name: 'Дядя',
    lastName: 'Фёдор',
    photo: '20',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Обучается',
  },
  {
    id: v1(),
    name: 'Буба',
    lastName: 'Бубенцов',
    photo: '21',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Илья',
    lastName: 'Анташкевич',
    photo: '22',
    info: 'Художник и иллюстратор. Рисую обаятельные и точные портреты из окружающей жизни.',
    status: 'Отчислен',
  },
  {
    id: v1(),
    name: 'Леброн',
    lastName: 'Джеймс',
    photo: '23',
    info: 'Звуковой художник, куратор и музыкальный продюсер. Работал как аранжировщик и композитор с популярными исполнителями.',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Натали',
    lastName: 'Трамп',
    photo: '24',
    info: 'Изучаю цифровой дизайн, программирование и управление проектами.',
    status: 'Обучается',
  },
  {
    id: v1(),
    name: 'Валентина',
    lastName: 'Матанина',
    photo: '25',
    info: 'Звуковой художник, куратор и музыкальный продюсер. Работал как аранжировщик и композитор с популярными исполнителями.',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Лев',
    lastName: 'Кошкин',
    photo: '26',
    info: 'Изучаю цифровой дизайн, программирование и управление проектами.',
    status: 'Отчислен',
  },
  {
    id: v1(),
    name: 'Антоха',
    lastName: 'Антонов',
    photo: '27',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Обучается',
  },
  {
    id: v1(),
    name: 'Александр',
    lastName: 'Александров',
    photo: '28',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis totam id dolorem reprehenderit perferendis, nostrum sequi quod consequatur veritatis? Numquam asperiores, aliquid sit natus quod dolorem autem. Eius, iste eveniet.',
    status: 'Закончил',
  },
  {
    id: v1(),
    name: 'Дим',
    lastName: 'Димыч',
    photo: '29',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Отчислен',
  },
  {
    id: v1(),
    name: 'Дядя',
    lastName: 'Фёдор',
    photo: '30',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Обучается',
  },
  {
    id: v1(),
    name: 'Дим',
    lastName: 'Димыч',
    photo: '31',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Отчислен',
  },
  {
    id: v1(),
    name: 'Дядя',
    lastName: 'Фёдор',
    photo: '32',
    info: 'Люблю пепперони и старые серии смешариков. А вы были на Таити?',
    status: 'Обучается',
  },
];
